config/routes.rb
KonzumSocial::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
              controllers: {omniauth_callbacks: "authentications"}
  resources :authentications
  resources :dashboard do
    collection do
      get 'orders'
      get 'friends'
      get 'shopping_lists'
      get 'liked_products'
      get 'favorite_products'
      get 'recipes'
      get 'browse_customers'
    end
  end
  resources :categories
  resources :products do
    member do
      post 'share_on_facebook'
      post 'share_in_email'
    end
  end
  resources :users do
    member do
      get 'profile'
    end
  end
  resources :carts do
    member do
      post 'checkout'
    end
  end
  resources :cart_items
  resources :orders
  resources :friendships
  resources :likes
  resources :favorites
  resources :ingredients
  resources :recipes do
    member do 
      get 'add_all_to_cart'
    end
  end
  resources :shopping_lists do 
    member do 
      get 'add_all_to_cart'
    end
  end
  resources :list_items
  resources :list_users
  get "user/:id/profile/orders" => "users#profile_orders", :as => 'profile_orders'
  get "user/:id/profile/likes" => "users#profile_likes", :as => 'profile_likes'
  get "user/:id/profile/favorites" => "users#profile_favorites", :as => 'profile_favorites'
  get "user/:id/profile/recipes" => "users#profile_recipes", :as => 'profile_recipes'
  root :to => "dashboard#index"

  

end

app/controllers/dashboard_controller.rb
require 'bootstrap_pagination_helper'
require 'will_paginate/array'

class DashboardController < ApplicationController
  before_filter :check_for_authentication, :only => [:index]
  before_filter :authenticate_user!, :except => [:index]

  def index
    @cart = current_cart
    @user_activities = UserActivity.where(:user_id => current_user.confirmed_friends.collect{|f| f.id}).order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
  end

  def orders
    @cart = current_cart
    @orders = current_user.orders.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)

  end

  def friends
    @cart = current_cart
    @friends = current_user.confirmed_friends.paginate(:page => params[:page], :per_page => 10)
  end

  def liked_products
    @cart = current_cart
    @likes = current_user.likes.paginate(:page => params[:page], :per_page => 15)
  end

  def favorite_products
    @cart = current_cart
    @favorites = current_user.favorites.paginate(:page => params[:page], :per_page => 15)
  end

  def recipes
    @cart = current_cart    
    @recipes = current_user.recipes
  end

  def shopping_lists
    @cart = current_cart
    @shopping_lists = current_user.shopping_lists
  end

  def browse_customers
    @cart = current_cart
    @other_users = User.where.not(id: current_user).paginate(page:  params[:page], per_page: 15, order: 'last_name')
  end

  def check_for_authentication
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/views/dashboard/_navigation_sidebar.html.erb
<div class="span3"> 
  <div class="well" style="padding: 8px 0;">
    <ul class="nav nav-list">
      <li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'index' %>"><%= link_to "<i class=\"icon-home\"></i> Home".html_safe, dashboard_index_path %></li>
      <li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'friends' %>"><%= link_to "<i class=\"icon-group\"></i> Friends #{friend_request_notification}".html_safe, friends_dashboard_index_path %></li>
      <li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'orders' %>"><%= link_to "<i class=\"icon-shopping-cart\"></i> Orders".html_safe, orders_dashboard_index_path %></li>
      <li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'shopping_lists' %>"><%= link_to "<i class=\"icon-list\"></i> Shopping lists".html_safe, shopping_lists_dashboard_index_path %></li>
      <li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'liked_products' %>"><%= link_to "<i class=\"icon-thumbs-up\"></i> Liked products".html_safe, liked_products_dashboard_index_path %></li>
        <li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'favorite_products' %>"><%= link_to "<i class=\"icon-heart\"></i> Favorites".html_safe, favorite_products_dashboard_index_path %></li>
      <li class="<%= 'active' if (params[:controller] == 'dashboard' && params[:action] == 'recipes') || params[:controller] == 'recipes' %>"><%= link_to "<i class=\"icon-food\"></i> Recipes".html_safe, recipes_dashboard_index_path %></li>
      <li class="divider"></li>
      <li class="<%= 'active' if params[:controller] == 'dashboard' && params[:action] == 'browse_customers' %>"><%= link_to "<i class=\"icon-search\"></i> Browse customers".html_safe, browse_customers_dashboard_index_path %></li>
      <li class="divider"></li>      
      <li class="<%= 'active' if params[:controller] == 'devise/registrations' && params[:action] == 'edit' %>"><%= link_to "<i class=\"icon-wrench\"></i> Settings".html_safe, edit_user_registration_path %></li> 
      <li><%= link_to "<i class=\"icon-share\"></i> Logout".html_safe, destroy_user_session_path, :method => :delete %></li>
    </ul>
  </div>
  <% unless params[:controller] == 'devise/registrations' && params[:action] == 'edit' %>
    <div class="well" style="text-align: center;">
      <% if session[:active_recipe] == nil && session[:active_shopping_list] == nil %>
          <h5 class="muted"><%= image_tag 'shopping-cart.png' %> Your Konzum cart</h5>
          <div id="cart">
            <%= render :partial => 'shared/cart' %>
          </div>
      <% elsif session[:active_shopping_list] != nil %>
          <h5 class="muted"><%= image_tag 'shopping_list.png' %> Your Shopping List</h5>
          <div id="shopping_list">
            <%= render :partial => 'shared/shopping_list' %>
          </div>
      <% else %>
          <h5 class="muted"><%= image_tag 'ingredients.png' %> Your Ingredients</h5>
          <div id="ingredients">
            <%= render :partial => 'shared/ingredients' %>
          </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/dashboard/browse_customers.html.erb
<%= render :partial => "dashboard/navigation_sidebar" %>
<div class="span9">

  <div class="well well-small">
    <h4 style="margin-left: 15px;"><i class="icon-search"/></i> Browse customers</h4>
  </div>

  <div class="pagination">
    <%= will_paginate @other_users, :previous_label => 'Previous', :next_label => 'Next', :renderer => 'BootstrapPaginationHelper::LinkRenderer'%>
  </div>

  <table class="table table-striped">
    <% @other_users.each do |user| %>
      <%unless friendship_status(user, current_user) =='Pending' %>      
        <tr>
          <td style="width: 55px;">
            <%= link_to (image_tag user.profile_picture('square'), :class => "imageClip pull-left"), profile_user_path(user), :class => "thumbnail pull-left", :style => "width: 50px; height: 50px;", :title => user.full_name %>
          </td>
          <td><%= link_to user.full_name, profile_user_path(user.id) %></td>
          <td>
            <%= user.gender == 'M' ? '<i class="icon-male"></i> Male'.html_safe : '<i class="icon-female"></i> Female'.html_safe %>
          </td>
          <td>
            <%= user.email %>
          </td>
          <% fs = friendship_status(current_user, user) %>
          <% if fs == 'None' %>
            <td><%= link_to "<i class=\"icon-plus\"> Send friend request</i>".html_safe, friendships_path(friend_id: user), method: :post, :class => "btn btn-primary btn-small" %></td>
          <% elsif fs == 'OK' %>
          <!-- dummy id 0 for friendship is OK, I don't know why it isn't automatically recognized -->
            <td><%= link_to "<i class=\"icon-minus\"> Remove from friends</i>".html_safe, friendship_path(friend_id: user, id:0), method: :delete, :class => "btn btn-danger btn-small" %></td>            
          <% else %>
            <td><%= link_to "<i class=\"icon-minus\"> Remove pending</i>".html_safe, friendship_path(friend_id: user, id: 0), method: :delete, :class => "btn btn-danger btn-small" %></td> 
          <% end %>
        </tr>
      <%end%>
    <% end %>
  </table>

  <div class="pagination">
    <%= will_paginate @other_users, :previous_label => 'Previous', :next_label => 'Next', :renderer => 'BootstrapPaginationHelper::LinkRenderer'%>
  </div>
</div>

app/views/dashboard/favorite_products.html.erb
<%= render :partial => "dashboard/navigation_sidebar" %>
<div class="span9">
  <div class="well well-small">
    <h4 style="margin-left: 15px;"><i class="icon-heart"/></i> Favorites</h4>
  </div>

  <% unless flash[:fav_notice].blank? %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice].html_safe %>
    </div>
  <% end %>  

  <% if @favorites.blank? %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
        You don't have any products in favorites.
    </div>
  <% else %>
    <%= render :partial => 'shared/users_favorite_products', :locals => {:favorites => @favorites} %>
  <% end %>

</div>

app/views/dashboard/friends.html.erb
<%= render :partial => "dashboard/navigation_sidebar" %>
<div class="span9">
  <div class="well well-small">
    <h4 style="margin-left: 15px;"><i class="icon-group"/></i> Friends</h4>
  </div>

  <% if current_user.inverse_friendships.select{|e| e.pending }.length > 0 %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>Heads up!</strong> You have <%= pluralize(current_user.inverse_friendships.select{|e| e.pending }.length, "new friend request") %>!
  </div>
  <% current_user.inverse_friendships.select{|e| e.pending }.each do |request| %>
    <div class="row-fluid">
      <div class="span12 well">
        <div class="span1">
          <%= link_to (image_tag request.user.profile_picture('square'), :class => "imageClip"), profile_user_path(request.user), :class => "thumbnail", :style => "width: 50px; height: 50px; display: inline-block;", :title => request.user.full_name %>   
        </div>
        <div class="span3">
          <p><strong><%=  link_to request.user.full_name, profile_user_path(request.user) %></strong></p>
          <p><%= request.user.email %></p>
        </div>
        <div class="span8">
          <div class="button-toolbar pull-right">
              <%= link_to "<i class=\"icon-ok\"> Accept</i>".html_safe, friendship_path(:friend_id => request.user.id, :id => current_user.id), method: :put, :class => "btn btn-primary btn-small" %>
              <%= link_to "<i class=\"icon-remove\"> Reject</i>".html_safe, friendship_path(:friend_id => request.user.id, :id => current_user.id), method: :delete, :class => "btn btn-danger btn-small" %>
            </div>        
        </div>
      </div>
    </div>
    <% end %>
    <legend>Your friends</legend>
  <% else %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">×</button>
      You don't have any friend requests!
    </div>
  <% end %>

  <% i = 0 %>
  <% current_user.confirmed_friends.each do |friend| %>
    <% if i % 2 == 0 %>
    <div class="row-fluid">
      <% end %>
      <% i += 1 %>
      <div class="span6 well">
        <div class="row-fluid">
          <div class="span3">
            <%= link_to (image_tag friend.profile_picture('square'), :class => "imageClip"), profile_user_path(friend), :class => "thumbnail", :style => "width: 50px; height: 50px; display: inline-block;", :title => friend.full_name %>
          </div>
          <div class="span9">
            <%= link_to "<i class=\"icon-remove\"></i>".html_safe, friendship_path(:friend_id => friend.id, :id => current_user.id), method: :delete, :class => "pull-right", :title => "Remove from friends" %>            
            <p><strong><%= link_to friend.full_name, profile_user_path(friend) %></strong></p>
            <p><%= friend.email %></p>
            <span class=" badge badge-warning"><%= friend.orders.length %> orders</span> <span class=" badge badge-info"><%= friend.friends.length %> friends</span>
          </div>
        </div>
      </div>
      <% if i % 2 == 0 %>
    </div>
    <% end %>
  <% end %>

  <div class="pagination">
    <%= will_paginate @friends, :previous_label => 'Previous', :next_label => 'Next', :renderer => 'BootstrapPaginationHelper::LinkRenderer'%>
  </div>

</div>

app/views/dashboard/index.html.erb
<%= render :partial => "dashboard/navigation_sidebar" %>
<div class="span9">
  <div class="well well-small">
    <h4 style="margin-left: 15px;"><i class="icon-list"/></i> News feed</h4>
  </div>

  <div class="pagination">
    <%= will_paginate @user_activities, :previous_label => 'Previous', :next_label => 'Next', :renderer => 'BootstrapPaginationHelper::LinkRenderer'%>
  </div>

  <%= render :partial => 'shared/list_user_activities', :locals => {:user_activities => @user_activities} %>

  <div class="pagination">
    <%= will_paginate @user_activities, :previous_label => 'Previous', :next_label => 'Next', :renderer => 'BootstrapPaginationHelper::LinkRenderer'%>
  </div>

</div>

app/views/dashboard/liked_products.html.erb
<%= render :partial => "dashboard/navigation_sidebar" %>
<div class="span9">
  <div class="well well-small">
    <h4 style="margin-left: 15px;"><i class="icon-thumbs-up"/></i> Liked products</h4>
  </div>

  <% unless flash[:like_notice].blank? %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice].html_safe %>
    </div>
  <% end %>

  <% if @likes.blank? %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
        You haven't liked any product yet.
    </div>
  <% else %>
    <%= render :partial => 'shared/users_liked_products', :locals => {:likes => @likes} %>
  <% end %>

</div>

app/views/dashboard/orders.html.erb
<%= render :partial => "dashboard/navigation_sidebar" %>
<div class="span9">
  <div class="well well-small">
    <h4 style="margin-left: 15px;"><i class="icon-shopping-cart"/></i> Orders</h4>
  </div>

  <div class="pagination">
    <%= will_paginate @orders, :previous_label => 'Previous', :next_label => 'Next', :renderer => 'BootstrapPaginationHelper::LinkRenderer'%>
  </div>
  
  <% if @orders.blank? %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
        You haven't placed any orders yet.
    </div>
  <% else %>
    <%= render :partial => 'shared/users_orders', :locals => {:orders => @orders} %>
  <% end %>

  <div class="pagination">
    <%= will_paginate @orders, :previous_label => 'Previous', :next_label => 'Next', :renderer => 'BootstrapPaginationHelper::LinkRenderer'%>
  </div>

</div>

app/views/dashboard/recipes.html.erb
<%= render :partial => "dashboard/navigation_sidebar" %>
<div class="span9">
  <div class="well well-small">
    <h4 style="margin-left: 15px;">
    <i class="icon-food"/></i> Recipes
    <%= link_to "<i class=\"icon-plus\"></i> Add recipe".html_safe, new_recipe_path, :class => "btn btn-primary pull-right", disabled: !session[:active_recipe].nil? %>
    </h4>

  </div>

  <% if @recipes.blank? %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
        You don't have any recipes yet.
    </div>
  <% else %>
    <%= render partial: 'shared/users_recipes', :locals => {:recipes => @recipes} %>
  <% end %>  
</div>

app/views/dashboard/shopping_lists.html.erb
<%= render 'dashboard/navigation_sidebar' %>
<div class="span9">
  <div class="well well-small">
    <h4 style="margin-left: 15px;">
      <i class="icon-list"/></i> Shopping lists
        <%= link_to "<i class=\"icon-plus\"></i> Add Shopping List".html_safe, new_shopping_list_path, :class => "btn btn-primary pull-right", disabled: !session[:active_shopping_list].nil? %>
    </h4>
  </div>

  <% if @shopping_lists.blank? %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
        You are not a member of any shopping lists.
    </div>
  <% else %>
    <%= render partial: 'shared/users_shopping_lists', locals: {shopping_lists: @shopping_lists} %>
  <% end %>  
</div>