config/routes.rb
KonzumSocial::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
              controllers: {omniauth_callbacks: "authentications"}
  resources :authentications
  resources :dashboard do
    collection do
      get 'orders'
      get 'friends'
      get 'shopping_lists'
      get 'liked_products'
      get 'favorite_products'
      get 'recipes'
      get 'browse_customers'
    end
  end
  resources :categories
  resources :products do
    member do
      post 'share_on_facebook'
      post 'share_in_email'
    end
  end
  resources :users do
    member do
      get 'profile'
    end
  end
  resources :carts do
    member do
      post 'checkout'
    end
  end
  resources :cart_items
  resources :orders
  resources :friendships
  resources :likes
  resources :favorites
  resources :ingredients
  resources :recipes do
    member do 
      get 'add_all_to_cart'
    end
  end
  resources :shopping_lists do 
    member do 
      get 'add_all_to_cart'
    end
  end
  resources :list_items
  resources :list_users
  get "user/:id/profile/orders" => "users#profile_orders", :as => 'profile_orders'
  get "user/:id/profile/likes" => "users#profile_likes", :as => 'profile_likes'
  get "user/:id/profile/favorites" => "users#profile_favorites", :as => 'profile_favorites'
  get "user/:id/profile/recipes" => "users#profile_recipes", :as => 'profile_recipes'
  root :to => "dashboard#index"

  

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :ingredients, dependent: :destroy
  has_many :products, through: :ingredients

  def total_current_amount
    ingredients.inject(0){ |sum, item| sum + item.quantity * item.product.price}
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :add_all_to_cart]
  before_action :set_cart

  def new
    @recipe = current_user.recipes.build
    @recipe.save
    session[:active_recipe] = @recipe.id
    session[:active_shopping_list] = nil
  end

  def show  
    session[:active_shopping_list] = nil
  end

  def add_all_to_cart
    @recipe.ingredients.each do |ingredient|
      cart_item = current_cart.add_product(ingredient.product.id)
      cart_item.quantity += ingredient.quantity - 1
      cart_item.save
    end
    redirect_to :back
  end

  def edit
    session[:active_recipe] = @recipe.id
    session[:active_shopping_list] = nil
  end

  def update
    params_recipe = params.require(:recipe).permit(:name, :instructions)
    if params[:save]
      @recipe.update(params_recipe)
      @recipe.save
      session[:active_recipe] = nil
      redirect_to recipes_dashboard_index_url
    elsif params[:modify_ingredients]
      @recipe.update(params_recipe)
      @recipe.save
      redirect_to categories_url
    end      
  end


  def destroy
    if params[:purge]
      @recipe.ingredients.destroy_all
      redirect_to edit_recipe_url
    else
      if session[:active_recipe] == @recipe.id
        session[:active_recipe] = nil
      end
      @recipe.destroy
      respond_to do |format|
        format.html { redirect_to :back, notice: 'Recipe destroyed.' }
        format.json { head :ok }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_cart
    @cart = current_cart
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def get_active_recipe
    recipe_id = session[:active_recipe]
    return Recipe.find(recipe_id)
  end
  
end

app/views/recipes/_recipe_form.html.erb
<div class="well">
  <%= form_for(@recipe, :html => { :class => "form-horizontal", :method => :put }) do |f| %>

  <legend>Modify Recipe</legend>

  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name, :class => "input-xxlarge" %>   
    </div>
  </div>
  
  <div class="control-group">
    <div class="controls">
      <%= button_tag type: "submit", class: "btn btn-primary", name: "modify_ingredients" do %> 
        <i class="icon-cog"></i> Modify Ingredients
      <% end %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <table class="table table-striped">
        <% @recipe.ingredients.each do |ingredient| %>
        <tr>
          <td style="width: 55px;">
            <%= link_to (image_tag ingredient.product.image_small, :class => "imageClip pull-left"), product_path(ingredient.product), :class => "thumbnail pull-left", :style => "width: 50px; height: 50px;", :title => ingredient.product.name %>
          </td>
          <td><%= ingredient.quantity %>&times; <%= ingredient.product.name %></td>
          <td><%= link_to "<i class=\"icon-remove\"></i>".html_safe, ingredient_path(ingredient), :method => :delete %>
        </tr>
        <% end %>
      </table>
      </div>
  </div>

  <div class="control-group">
    <%= f.label :instructions, :class => "control-label" %>
    <div class="controls">
      <%= f.text_area :instructions, rows: 6, class: "input-xxlarge" %>   
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit "Save", class: "btn btn-primary", name: "save" %>
    </div>
  </div>

  <% end %>
</div>

app/views/recipes/edit.html.erb
<%= render :partial => "dashboard/navigation_sidebar" %>
<div class="span9">
  <div class="well well-small">
    <h4 style="margin-left: 15px;">
      <i class="icon-food"/></i> Recipes
    </h4>
  </div>
<%= render 'recipe_form' %>
</div>

app/views/recipes/new.html.erb
<%= render :partial => "dashboard/navigation_sidebar" %>
<div class="span9">
  <div class="well well-small">
    <h4 style="margin-left: 15px;">
      <i class="icon-food"/></i> Recipes
    </h4>
  </div>
<%= render 'recipe_form' %>
</div>

app/views/recipes/show.html.erb
<%= render :partial => "dashboard/navigation_sidebar" %>
<div class="span9">
  <div class="well well-small">
    <h4 style="margin-left: 15px;">
      <i class="icon-food"/></i> Recipes
    </h4>
  </div>

  <h4><%= @recipe.name %><small> by <%= link_to @recipe.user.full_name, profile_user_path(@recipe.user) %></small></h4>
  <hr></hr>
    <h5>Ingredients</h5>
    <table class="table table-striped">  
      <% @recipe.ingredients.each do |ingredient| %>
      <tr>
        <td style="width: 55px;">
          <%= link_to (image_tag ingredient.product.image_small, :class => "imageClip pull-left"), product_path(ingredient.product), :class => "thumbnail pull-left", :style => "width: 50px; height: 50px;", :title => ingredient.product.name %>
        </td>
        <td><%= ingredient.quantity %>&times; <%= ingredient.product.name %></td>
        <td><%= number_to_currency(ingredient.product.price * ingredient.quantity, :unit => "HRK ", :separator => ',', :delimiter => '.') %></td>
        <td>
          <%= link_to "<i class=\"icon-info\"> Product info</i>".html_safe, product_path(ingredient.product), :class => "btn btn-small" %>
        </td>
      </tr>
      <% end %>
      <tr>
        <th></th>
        <th>Total:</th>
        <th><%= number_to_currency(@recipe.total_current_amount, :unit => "HRK ", :separator => ',', :delimiter => '.') %><th>
      </tr>
    </table>
    <%= link_to "<i class=\"icon-plus\"></i> Add all ingredients to cart".html_safe, add_all_to_cart_recipe_path(@recipe), :class => "btn btn-primary" %>
   <hr></hr>
    <h5>Instructions</h5>  
    <%= @recipe.instructions %>
</div>