config/routes.rb
KonzumSocial::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
              controllers: {omniauth_callbacks: "authentications"}
  resources :authentications
  resources :dashboard do
    collection do
      get 'orders'
      get 'friends'
      get 'shopping_lists'
      get 'liked_products'
      get 'favorite_products'
      get 'recipes'
      get 'browse_customers'
    end
  end
  resources :categories
  resources :products do
    member do
      post 'share_on_facebook'
      post 'share_in_email'
    end
  end
  resources :users do
    member do
      get 'profile'
    end
  end
  resources :carts do
    member do
      post 'checkout'
    end
  end
  resources :cart_items
  resources :orders
  resources :friendships
  resources :likes
  resources :favorites
  resources :ingredients
  resources :recipes do
    member do 
      get 'add_all_to_cart'
    end
  end
  resources :shopping_lists do 
    member do 
      get 'add_all_to_cart'
    end
  end
  resources :list_items
  resources :list_users
  get "user/:id/profile/orders" => "users#profile_orders", :as => 'profile_orders'
  get "user/:id/profile/likes" => "users#profile_likes", :as => 'profile_likes'
  get "user/:id/profile/favorites" => "users#profile_favorites", :as => 'profile_favorites'
  get "user/:id/profile/recipes" => "users#profile_recipes", :as => 'profile_recipes'
  root :to => "dashboard#index"

  

end

app/views/shared/_cart.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $('a[disabled=disabled]').click(function(event){
        event.preventDefault();
        return false; // Prevent link from following its href
    });
  });
</script>

<% unless @cart.cart_items.blank? %>
  <table class="table table-condensed" style="font-size: small;">
    <% @cart.cart_items.sort.each do |item|%>
      <% if item == @current_item %>
        <tr id="current_item">
      <% else %>
        <tr>
      <% end %>
          <td><%= item.quantity %> &times; <%= item.product.name %></td>
          <td><%= number_to_currency(item.product.price * item.quantity, :separator => ',', :delimiter => '.', :unit => '') %></td>
          <td><%= link_to "<i class=\"icon-remove\"></i>".html_safe, cart_item_path(item), :method => :delete, :remote => true %>
      </tr>
    <% end %>
    <tr>
      <th>Total:</th>
      <th><%= number_to_currency(@cart.total_amount, :separator => ',', :delimiter => '.', :unit => '') %><th>
    </tr>
  </table>
<% else %>
  <div class="well">
    <small>Your cart is currently empty.</small>
  </div>
<% end %>

<div class="btn-group">
  <%= link_to "<i class=\"icon-shopping-cart\"> Checkout</i>".html_safe, "#orderModal", :class => "btn btn-primary", :id => @cart.cart_items.blank? ? "" : "checkout", :data_toggle => "modal", :disabled => @cart.cart_items.blank? %>
  <%= link_to "<i class=\"icon-trash\"> Empty cart</i>".html_safe, cart_path(@cart), :class => "btn btn-danger", :id => "empty-cart", :method => :delete, :disabled => @cart.cart_items.blank? %>
</div>

<%= render :partial => "shared/order_modal" %>

app/views/shared/_category_nav_list.html.erb
<script>
$(document).ready(function () {
  $('label.tree-toggler').click(function () {
    $(this).parent().children('ul.tree').toggle(300);
  });
});
</script>

<div class="well" style="padding: 8px 0;">
  <div>
    <ul class="nav nav-list">
      <%= get_cached_categories_list.html_safe %>
    </ul>
  </div>
</div>

app/views/shared/_ingredients.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $('a[disabled=disabled]').click(function(event){
        event.preventDefault();
        return false; // Prevent link from following its href
    });
  });
</script>

<% unless get_active_recipe.ingredients.blank? %>
  <table class="table table-condensed" style="font-size: small;">
    <% get_active_recipe.ingredients.sort.each do |item|%>
      <% if item == @current_item %>
        <tr id="current_item">
      <% else %>
        <tr>
      <% end %>
          <td><%= item.quantity %> &times; <%= item.product.name %></td>
          <td><%= number_to_currency(item.product.price * item.quantity, :separator => ',', :delimiter => '.', :unit => '') %></td>
          <td><%= link_to "<i class=\"icon-remove\"></i>".html_safe, ingredient_path(item), :method => :delete, :remote => true %>
      </tr>
    <% end %>
  </table>
<% else %>
  <div class="well">
    <small>You haven't selected any ingredients.</small>
  </div>
<% end %>

<div class="btn-group">
  <%= link_to "<i class=\"icon-save\"> Save</i>".html_safe, edit_recipe_path(get_active_recipe), :class => "btn btn-primary", disabled: get_active_recipe.ingredients.blank? %>
  <%= link_to "<i class=\"icon-trash\"> Delete All</i>".html_safe, recipe_path(get_active_recipe, purge: true), :class => "btn btn-danger", method: :delete, disabled: get_active_recipe.ingredients.blank? %>
</div>

app/views/shared/_invite_friends_modal.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $("#invite").click(function(){
      if ($(this).prop('disabled', 'disabled')) {
        $("#inviteFriendsModal").modal('show');
      };
    });
  });
</script>

<div id="inviteFriendsModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Invite friends</h3>
  </div>
  <div class="modal-body">
    <h5>Your friends:</h5>
    <div id="invite-table">
    <%= render "list_users/invite_table" %>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"> Close</i></button>
  </div>
</div>

app/views/shared/_list_user_activities.html.erb
<% user_activities.each do |activity| %>
    <div class="media">
      <%= link_to (image_tag activity.user.profile_picture('square'), :class => "imageClip pull-left"), profile_user_path(activity.user), :class => "thumbnail pull-left", :style => "width: 50px; height: 50px;", :title => activity.user.full_name %>
      <div class="media-body">

        <% if activity.feedable_type == 'PRODUCT_LIKE' %>
          <h4 class="media-heading"><%= link_to activity.user.full_name, profile_user_path(activity.user) %> liked new product</h4>
          <p>
            <%= activity.user.first_name %> liked product <%= link_to activity.product.name, product_path(activity.product) %> in <%= link_to activity.product.leaf_category.name, category_path(activity.product.leaf_category) %> product category.
          </p>
          <%= render :partial => 'shared/media_timebar', :locals => {:activity => activity} %>
          <%= render :partial => 'shared/media_product', :locals => {:activity => activity} %>
        <% elsif activity.feedable_type == 'PRODUCT_FAVORITE' %>
          <h4 class="media-heading"><%= link_to activity.user.full_name, profile_user_path(activity.user) %> added new product in <%= activity.user.gender == 'M' ? 'his' : 'her' %> favorites</h4>
          <p>
            <%= activity.user.first_name %> added product <%= link_to activity.product.name, product_path(activity.product) %> from <%= link_to activity.product.leaf_category.name, category_path(activity.product.leaf_category) %> product category in <%= activity.user.gender == 'M' ? 'his' : 'her' %> favorites.
          </p>
          <%= render :partial => 'shared/media_timebar', :locals => {:activity => activity} %>
          <%= render :partial => 'shared/media_product', :locals => {:activity => activity} %>
        <% elsif activity.feedable_type == 'ORDER_CHECKOUT' %>
          <h4 class="media-heading"><%= link_to activity.user.full_name, profile_user_path(activity.user) %> placed new order</h4>
          <p>
            <%= activity.user.first_name %> placed order with <strong><%= activity.order.order_items.length %></strong> products.
          </p>
          <%= render :partial => 'shared/media_timebar', :locals => {:activity => activity} %>
          <%= render :partial => 'shared/media_order', :locals => {:activity => activity} %>
        <% end %>
      </div>
    </div>
<% end %>

app/views/shared/_media_order.html.erb
<div class="media">
  
  <div class="media-body">
    <p>
      <%= render :partial => 'shared/users_orders', :locals => {:orders => [activity.order]} %>
    </p>
  </div>
</div>

app/views/shared/_media_product.html.erb
<div class="media">
  <%= link_to (image_tag activity.product.image_small, :class => "imageClip pull-left"), product_path(activity.product), :class => "thumbnail pull-left", :style => "width: 50px; height: 50px;", :title => activity.product.name %>
  <div class="media-body">
    <p>
      <small><strong><%= activity.product.name %></strong></small><br />
      <small><%= render_category_path(activity.product.leaf_category).html_safe %></small><br />
      <small><b>Price: </b><%= number_to_currency(activity.product.price, :unit => "HRK ", :separator => ',', :delimiter => '.') %></small><br />
      <p>
      <%= add_btn_helper(activity.product, :small) %></p>
    </p>
  </div>
</div>

app/views/shared/_media_timebar.html.erb
<p>
  <i class="icon-calendar"></i> <%= activity.created_at.to_date.to_formatted_s(:long_ordinal) %> 
  | <i class="icon-time"></i> <%= activity.created_at.strftime("%H:%M") %>
</p>

app/views/shared/_order_modal.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $("#checkout").click(function(){
      if ($(this).prop('disabled', 'disabled')) {
        $("#orderModal").modal('show');
      };
    });
  });
</script>

<div id="orderModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Confirm order</h3>
  </div>
  <div class="modal-body">
    <p>This is only a test application for generating product recommendations, and your order will not be processed nor charged. Please confirm your order.</p>
    <h5>Products in your cart:</h5>
    <% unless @cart.cart_items.blank? %>
      <table class="table table-striped" style="font-size: small;">
        <% @cart.cart_items.sort.each do |item|%>
          <tr>
            <td><%= item.quantity %> &times; <%= item.product.name %></td>
            <td><%= number_to_currency(item.product.price * item.quantity, :separator => ',', :delimiter => '.', :unit => 'HRK ') %></td>
          </tr>
        <% end %>
        <tr>
          <th>Total:</th>
          <th><%= number_to_currency(@cart.total_amount, :separator => ',', :delimiter => '.', :unit => 'HRK ') %>
        </tr>
      </table>
    <% end %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"> Cancel</i></button>
    <%= link_to "<i class=\"icon-ok\"> Confirm</i>".html_safe, checkout_cart_path(@cart), :class => "btn btn-primary", :method => :post %>
  </div>
</div>

app/views/shared/_popular_friends_products_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Rating</td>
      <th></th>
      <th>Product name</th>
      <th>Price</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% popular_products.each do |rec| %>
      <tr>
        <td style="width: 180px;">
          <div>
            Rating: <span class="pull-right strong"><%= ((rec.factor.to_f/max_factor.to_f)*100).to_i %> %</span>
            <div class="progress progress-striped active">
              <div class="bar " style="width: <%= ((rec.factor.to_f/@max_factor.to_f)*100).to_i %>%;"></div>
            </div>
          </div>
        </td>
        <td style="width: 55px;">
          <%= link_to (image_tag rec.product.image_small, :class => "imageClip pull-left"), product_path(rec.product), :class => "thumbnail pull-left", :style => "width: 50px; height: 50px;", :title => rec.product.name %>
        </td>
        <td><%= truncate rec.product.name, :length => 45 %></td>
        <td><%= number_to_currency(rec.product.price, :unit => "HRK ", :separator => ',', :delimiter => '.') %></td>
        <td>
          <%= link_to "<i class=\"icon-info\"> Info</i>".html_safe, product_path(rec.product), :class => "btn btn-small" %>
        </td>
        <td>
          <%= add_btn_helper(rec.product) %>
        <td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_share_modal.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $('a[disabled=disabled]').click(function(event){
        event.preventDefault();
        return false; // Prevent link from following its href
    });
  });
  
  $(document).ready(function() {
    $("#share").click(function(){
      if ($(this).prop('disabled', 'disabled')) {
        $("#shareModal").modal('show');
      };
    });
  });
</script>

<div id="shareModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Publish product on your timeline</h3>
  </div>
  <div class="modal-body">
    <p>You will share product <%= link_to @product.name, product_path(@product) %> with your Facebook friends.</p>
    
    <div class="thumbnail clearfix">
      <table>
        <tr>
        <td>
          <%= image_tag @product.image_medium, :class => 'pull-left span12 clearfix', :style => 'margin-right:10px' %>
        </td>
        <td>
          <div class="caption" class="pull-left">
            <h4>      
              <%= @product.name %>
            </h4>
            <small><%= render_category_path(@product.leaf_category).html_safe %></small><br />
            <small><b>Price: </b><%= number_to_currency(@product.price, :unit => "HRK ", :separator => ',', :delimiter => '.') %></small><br />
            <small><b>Sales unit of measure: </b><%= @product.sales_unit_of_measure %></small><br />
            <small><b>Manufacturer: </b><%= @product.manufacturer %></small><br />
            <small><b>Supplier: </b><%= @product.supplier %></small><br />
            <small><b>Product description: </b><%= @product.description %></small><br />
          </div>
        </td>
      </tr>
      </table>
    </div>

  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"> Cancel</i></button>
    <%= link_to "<i class=\"icon-share-alt\"> Share</i>".html_safe, share_product_path(@product), :class => "btn btn-primary", :method => :post %>
  </div>
</div>

app/views/shared/_shopping_list.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $('a[disabled=disabled]').click(function(event){
        event.preventDefault();
        return false; // Prevent link from following its href
    });
  });
</script>

<% unless get_active_list.list_items.blank? %>
  <table class="table table-condensed" style="font-size: small;">
    <% get_active_list.list_items.sort.each do |item|%>
      <% if item == @current_item %>
        <tr id="current_item">
      <% else %>
        <tr>
      <% end %>
          <td><%= item.quantity %> &times; <%= item.product.name %></td>
          <td><%= number_to_currency(item.product.price * item.quantity, :separator => ',', :delimiter => '.', :unit => '') %></td>
          <td><%= link_to "<i class=\"icon-remove\"></i>".html_safe, list_item_path(item), :method => :delete, :remote => true %>
      </tr>
    <% end %>
  </table>
<% else %>
  <div class="well">
    <small>You haven't selected any products.</small>
  </div>
<% end %>

<div class="btn-group">
  <%= link_to "<i class=\"icon-save\"> Save</i>".html_safe, edit_shopping_list_path(get_active_list), :class => "btn btn-primary", disabled: get_active_list.list_items.blank? %>

  <%= link_to "<i class=\"icon-trash\"> Delete All</i>".html_safe, shopping_list_path(get_active_list, purge: true), :class => "btn btn-danger", method: :delete, disabled: get_active_list.list_items.blank? %>
</div>

app/views/shared/_users_liked_products.html.erb
<div class="pagination">
  <%= will_paginate likes, :previous_label => 'Previous', :next_label => 'Next', :renderer => 'BootstrapPaginationHelper::LinkRenderer'%>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Product name</th>
      <th>Unit</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% likes.select{|e| e.likeable_type == 'PRODUCT' }.each do |like| %>
      <tr>
        <td style="width: 55px;">
          <%= link_to (image_tag like.product.image_small, :class => "imageClip pull-left"), product_path(like.product), :class => "thumbnail pull-left", :style => "width: 50px; height: 50px;", :title => like.product.name %>
        </td>
        <td><%= truncate like.product.name, :length => 65 %></td>
        <td><%= like.product.sales_unit_of_measure %></td>
        <td><%= number_to_currency(like.product.price, :unit => "HRK ", :separator => ',', :delimiter => '.') %></td>
        <td>
          <%= link_to "<i class=\"icon-info\"> Info</i>".html_safe, product_path(like.product), :class => "btn btn-small" %>
        </td>
        <td>
          <%= add_btn_helper(like.product, :small) %>
        <td>
          <% if like.user == current_user%>
            <td><%= link_to "<i class=\"icon-remove\"></i>".html_safe, like_path(like), :method => :delete, :title => "Dislike" %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination">
  <%= will_paginate likes, :previous_label => 'Previous', :next_label => 'Next', :renderer => 'BootstrapPaginationHelper::LinkRenderer'%>
</div>

app/views/shared/_users_orders.html.erb
<div class="accordion">
  <div class="accordion-group">  
    <% orders.each do |order| %>
      <div class="accordion-heading">
        <%= image_tag 'shopping-cart.png', :style => "float:left; margin: 3px 10px 0 3px; height: 30px" %>
        <a class="accordion-toggle" data-toggle="collapse" href=<%= '#' + "order#{order.id}" %>><%= "Order No. #{order.id} (#{order.created_at.to_date.to_formatted_s(:long_ordinal)})" %></a>
      </div>
      <div id=<%= "order#{order.id}" %> class="accordion-body collapse">
        <div class="accordion-inner">
          <table class="table table-striped table-condensed">
            <thead>
              <tr>
                <th></th>
                <th>Product name</th>
                <th>Unit</th>
                <th>Quantity</th>
                <th>Price</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% order.order_items.each do |item| %>
                <tr>
                  <td style="width: 55px;">
                    <%= link_to (image_tag item.product.image_small, :class => "imageClip pull-left"), product_path(item.product), :class => "thumbnail pull-left", :style => "width: 50px; height: 50px;", :title => item.product.name %>
                  </td>
                  <td><%= truncate item.product.name, :length => 65 %></td>
                  <td><%= item.product.sales_unit_of_measure %></td>
                  <td><%= item.quantity %></td>
                  <td><%= number_to_currency(item.product.price * item.quantity, :unit => "HRK ", :separator => ',', :delimiter => '.') %></td>
                  <td>
                    <%= link_to "<i class=\"icon-info\"> Product info</i>".html_safe, product_path(item.product), :class => "btn btn-small" %>
                  </td>
                </tr>
              <% end %>
              <tr>
                <th></th>
                <th>Total:</th>
                <th></th>
                <th></th>
                <th><%= number_to_currency(order.total_current_amount, :unit => "HRK ", :separator => ',', :delimiter => '.') %><th>
              </tr>
            </tbody>
          </table>
          
          <div class="button-toolbar">
            <% if order.user == current_user %>
              <%= link_to "<i class=\"icon-trash\"></i> Delete order".html_safe, order_path(order), :class => "btn btn-danger", :method => :delete %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>