config/routes.rb
KonzumSocial::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
              controllers: {omniauth_callbacks: "authentications"}
  resources :authentications
  resources :dashboard do
    collection do
      get 'orders'
      get 'friends'
      get 'shopping_lists'
      get 'liked_products'
      get 'favorite_products'
      get 'recipes'
      get 'browse_customers'
    end
  end
  resources :categories
  resources :products do
    member do
      post 'share_on_facebook'
      post 'share_in_email'
    end
  end
  resources :users do
    member do
      get 'profile'
    end
  end
  resources :carts do
    member do
      post 'checkout'
    end
  end
  resources :cart_items
  resources :orders
  resources :friendships
  resources :likes
  resources :favorites
  resources :ingredients
  resources :recipes do
    member do 
      get 'add_all_to_cart'
    end
  end
  resources :shopping_lists do 
    member do 
      get 'add_all_to_cart'
    end
  end
  resources :list_items
  resources :list_users
  get "user/:id/profile/orders" => "users#profile_orders", :as => 'profile_orders'
  get "user/:id/profile/likes" => "users#profile_likes", :as => 'profile_likes'
  get "user/:id/profile/favorites" => "users#profile_favorites", :as => 'profile_favorites'
  get "user/:id/profile/recipes" => "users#profile_recipes", :as => 'profile_recipes'
  root :to => "dashboard#index"

  

end

app/models/list_user.rb
class ListUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :list,  class_name: 'ShoppingList', foreign_key: "list_id"
end

app/controllers/list_users_controller.rb
class ListUsersController < ApplicationController

  def show
  end
  
  def create
    @list_user = get_active_list.list_users.build(user_id: params[:user_id])
    @list_user.save
    respond_to do |format|
      format.html { redirect_to :back }
      format.js {render :action => 'refresh.js.erb'}
    end
  end

  def destroy 
    lu = ListUser.find_by(list_id: get_active_list, user_id: params[:user_id])
    lu.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.js {render :action => 'refresh.js.erb'}
    end
  end

  def get_active_list
    list_id = session[:active_shopping_list]
    return ShoppingList.find(list_id)
  end
end

app/helpers/list_users_helper.rb
module ListUsersHelper
end

app/views/list_users/_invite_table.html.erb
<table class="table table-striped" style="font-size: small;">
  <% current_user.confirmed_friends.each do |friend|%>
    <tr>
      <td><%= friend.full_name %></td>
      <% if ListUser.find_by(list_id: get_active_list, user_id: friend).blank? %>
        <td><%= link_to "<i class=\"icon-ok\"></i> Invite".html_safe, list_users_path(id: 0, user_id: friend), method: :post, :class => "btn btn-small", 'data-toggle' => "button", :remote => true %></td>  
        <% else %>    
        <td><%= link_to "<i class=\"icon-ok\"></i> Invite".html_safe, list_user_path(id: 0, user_id: friend), method: :delete, :class => "btn btn-small active", 'data-toggle' => "button", :remote => true %></td>    
      <% end %>
    </tr>
  <% end %>
</table>

app/views/list_users/refresh.js.erb
$('#invite-table').html("<%=j render :partial => 'list_users/invite_table' %>");